### ISSUE TITLE
Crash with syntax error/bad argument

### ISSUE THREAD

**Issue by kirbyfan64** [palmer-dabbelt/pconfigure#3] opened 2015-02-25 18:35 UTC
Examples:

```
ryan@DevPC-LX:~/stuff/pctst$ pconfigure -b
Unknown argument: '-b'
Aborted (core dumped)
ryan@DevPC-LX:~/stuff/pctst$ pconfigure
Error parsing line 1:
x = 1

talloc: access after free error - first free may be at src/pconfigure/main.c:142
Bad talloc magic value - access after free
Aborted (core dumped)
ryan@DevPC-LX:~/stuff/pctst$ 
```

**Comment by palmer-dabbelt** [comment] 2015-02-25 21:42
As far as I'm concerned, the first one is expected behavior -- it prints an error message and abort()s.  The reason I abort() instead of exit() is that it's easier to catch abort with GDB so it helps if I'm going to go and add new stuff.

I'd be OK with a patch that replaces these sorts of abort()s with "exit(1)" when built with -DNDEBUG.

The talloc message is a bug, but not really a critical one because pconfigure is just exiting anyway.  If you're willing to fix it then I'll accept a patch, otherwise I might get around to fixing it myself at some point -- you're welcome to submit a patch that's just a test case, that would make my life a tiny bit easier (and will make the bug less likely to get lost).

**Comment by kirbyfan64** [comment] 2015-02-25 22:47
@palmer-dabbelt Those explanations make sense.

I'd be happy to add a test case if I could figure out what those hashes in the test scripts are for...

**Comment by palmer-dabbelt** [comment] 2015-02-25 22:51
Ya, sorry, I forgot the tests were such a mess in pconfigure...

You can generate them from something like

tar -c . | gzip | base64 --encode

If you look at "test/pconfigure/harness.bash" you can see the reverse pipeline that extracts them.  This definately wasn't a good idea -- I've been using bash here document to generate test scripts in other projects, and it looks like my latest pbashc test works that way -- see "test/pbashc/harness2.bash".

I'd be all for converting all the test cases to use here documents... :)

**Comment by palmer-dabbelt** [comment] 2016-04-25 20:41
I'm closing this because I'm deprecating the C pconfigure.

**Closed by palmer-dabbelt** 2016-04-25 20:41 UTC
